CUDA_VISIBLE_DEVICES=4,5,6,7 python train_cross.py \
  --mode 'train' \
  --train_path ../ChID/train_data_1w_tok.json \
  --valid_path ../ChID/valid_data_tok.json \
  --idiom_max_length 30 \
  --stride \
  --stride_length 200 \
  --idiom_content_max_length 410 \
  --print_every 100 \
  --num_workers 16 \
  --batch_size 4 \
  --eval_batch_size 4 \
  --lr_retr 5e-5 \
  --lr_retr_min 5e-7 \
  --max_epochs 16 \
  --logdir ChID_1w_cross_stride_mask